# Generated by Django 4.2.7 on 2024-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgsrc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
