# Generated by Django 4.2.7 on 2024-01-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_name_alter_item_price_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
